### ISSUE TITLE
DLL is not allowed?

### ISSUE THREAD

**Issue by CavinHuang** [elugovoy/MQLMySQL-Project#1]
I import MQL4 to run, but it can not work.

my code:
```
 DB = MySqlConnect(Host, User, Password, Database, Port, Socket, ClientFlag);
    if (DB == -1) { 
      Print ("Connection failed! Error: "+MySqlErrorDescription);
      return ;
    } else { 
      Print ("Connected! DBID#",DB);
    }
```

logs:
```
Cannot call '..\libraries\MQLMySQL.dll::cMySqlDisconnect', DLL is not allowed

```

what happened for me?

**Comment by elugovoy** [comment]
You need to allow DLL Imports. In MetaTrader main menu please go to Tools -> Options, select Expert Advisors tab and set checkbox on Allow DLL imports
![Screen Shot 2020-01-10 at 5 23 50 PM](https://user-images.githubusercontent.com/2965249/72164404-4f018280-33ce-11ea-8af1-c3fceed97658.png)
