### ISSUE TITLE
Тестирование

### ISSUE THREAD

**Issue by Demal** [elugovoy/MQLMySQL-Project#2]
Здравствуйте, Евгений. У меня возникли проблемы. Для проверки ваших библиотек
я написал несколько скриптов на MQL5.  Вот `первый:
[Test.txt](https://github.com/elugovoy/MQLMySQL-Project/files/4087522/Test.txt)
А вот результаты скрипта
![2020-01-21_02-01-01](https://user-images.githubusercontent.com/26419074/72751623-aedc0280-3bf2-11ea-827f-4b5d31ff9b63.png)
Как видим файл ini не считался. Функция  ReadIni  не сработала. В чем моя ошибка?

**Comment by Demal** [comment]
Разобрался, некорректно сформировалось имя файла

**Comment by elugovoy** [comment]
Обратите внимание что если вы храните ini файл в одном из подкаталогов директории MQL5, то путь в mql программе должен идти к Data Folder (который может отличаться от пути к терминалу при включенном UAC OS Windows).
Для тестирования можно просто использовать абсолютные пути.
Успехов!
