### ISSUE TITLE
ошибка при компиляции  'function not define

### ISSUE THREAD

**Issue by Demal** [elugovoy/MQLMySQL-Project#3]
Уважаемый Евгений, не могли бы вы пояснить ситуацию. При компиляции вылетает ошибка "function not defined", хотя строчкой выше таже функция компилируется без
ошибок.
![2020-02-02_20-28-09](https://user-images.githubusercontent.com/26419074/73608915-e8513c80-45fa-11ea-9d1c-6b245697ddf2.png)

**Comment by elugovoy** [comment]
Приветствую.
По данному участку кода, это не представляется возможным.
Пожалуйста укажите версию терминала, а так же предоставьте участок кода от команды выборки данных в курсор (включая SELECT) и участок кода где описывается структура nowOR.
В этом случае я смогу определить причину возникновения ошибки.

**Comment by elugovoy** [comment]
Closed because no answer with details provided.
