### ISSUE TITLE
mql4 test script change

### ISSUE THREAD

**Issue by phantasz** [elugovoy/MQLMySQL-Project#4]
I had to make a change to find ini file. I believe the way it is coded now will only find file if mt4 is opened as administrator. 
This works instead:
INI = TerminalInfoString(TERMINAL_DATA_PATH)+"\\MQL4\\Scripts\\MyConnection.ini";

**Comment by elugovoy** [comment]
Sure, you right, but you can place your INI file anywhere on drive (where your OS user has appropriate rights), and just set fullpath in MQL code to.
Also, you may keep your database credentials inside MQL code, or write special functions to read them from windows registry keys (to keep credentials in registry).
