### ISSUE TITLE
 взаимодействие mt4 и mysql

### ISSUE THREAD

**Issue by Demal** [elugovoy/MQLMySQL-Project#5]
Уважаемый, Евгений, здравствуйте! Столкнулся со следующей проблемой. Не у всех терминалов, при прочих равных,  происходит соединение  с  БД. Фиксируется ошибка
Connection failed. Error:  Access denied user 'user_name'@'host' (using password:YES.  
Имя и пароль проверены.

**Comment by elugovoy** [comment]
Вероятнее всего, проблема с подключением у Вас в целом и библиотека не имеет к этому отношения
